---
run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - gocognit
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - staticcheck
    - unconvert
    - unused

linters-settings:
  gocognit:
    min-complexity: 30
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  goimports:
    local-prefixes: github.com/giantswarm/klausctl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
